---

# List of modules known to this role
_icingaweb2_modules_known_modules:
  - name: "grafana"
    git_url: "https://github.com/NETWAYS/icingaweb2-module-grafana.git"
  - name: "map"
    git_url: "https://github.com/nbuchwitz/icingaweb2-module-map.git"
  - name: "mapDatatype"
    git_url: "https://github.com/nbuchwitz/icingaweb2-module-mapDatatype.git"
  - name: "perfdatagraphs"
    git_url: "https://github.com/NETWAYS/icingaweb2-module-perfdatagraphs"
  - name: "perfdatagraphsinfluxdbv2"
    git_url: "https://github.com/NETWAYS/icingaweb2-module-perfdatagraphs-influxdbv2"
  - name: "perfdatagraphsinfluxdbv1"
    git_url: "https://github.com/NETWAYS/icingaweb2-module-perfdatagraphs-influxdbv1"
  - name: "perfdatagraphsgraphite"
    git_url: "https://github.com/NETWAYS/icingaweb2-module-perfdatagraphs-graphite"
_icingaweb2_modules_grafana_server_user: "grafana"
_icingaweb2_modules_grafana_server_group: "grafana"
